api/urls.py
from django import urls
# from django.db import router
from django.urls import path
from django.urls.conf import include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from api.api_url_routers import comment_router, post_router


urlpatterns = [
    path('tags/', views.tags, name='apitag'),
    path('categories/', views.categories, name='apicategories'),
    path('comments/', include(comment_router.urls)),
    path('posts/', include(post_router.urls)),

    path('likepost/', views.apilike, name='apilike'),
    path('dislikepost/', views.apidislike, name='apidislike'),
    path('acceptpost/', views.api_accept_post, name='api_accept_post'),
    path('acceptcomment/', views.api_accept_comment, name='api_accept_comment'),
    path('likecomment/', views.apilikecomment, name='apilikecomment'),
    path('dislikecomment/', views.apidislikecomment, name='apidislikecomment'),
    path('addtag/', views.add_tag, name='add_tag'),
    path('checkusername/', views.check_username, name='check_username'),
    path('gettag/', views.get_tag, name='get_tag'),
    path('getimage/', views.get_iamge, name='get_image'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('popular/', views.popular, name='popular'),
    path('', views.index, name='index'),
    path('<str:username>/newpost/', views.newpost, name='newpost'),
    path('<str:username>/<int:pk>/edit/', views.editpost, name='editpost'),
    path('<str:username>/<int:pk>/', views.showpost, name='showpost'),
    path('category/', views.categorytree, name='categorytree'),
    path('category/<str:name>', views.showcategory, name='showcategory'),
    path('tag/<str:name>/', views.showtag, name='showtag'),
    path('tags/', views.alltags, name='alltags'),
    path('about/', views.aboutus, name='aboutus'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from tinymce import models as tinymce_models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.translation import ugettext_lazy
from django.utils import timezone
from django.contrib.auth.password_validation import validate_password
from string import printable

# Create your models here.
class Tag(models.Model):
    class Meta:
        verbose_name = 'برچسب'
        verbose_name_plural = 'برچسب ها'

    name = models.CharField(
        verbose_name='برچسب',
        max_length=100,
    )
    accept_by_admin = models.BooleanField(
        verbose_name='برچسب تایید شده است',
        default=False,
    )
    
    def __str__(self):
        return self.name

class Category(models.Model):
    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'

    name = models.CharField(
        verbose_name='دسته بندی',
        max_length=100,
    )

    supercategory = models.ForeignKey(
        'Category',
        verbose_name='سر دسته',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.name

class Post(models.Model):
    class Meta:
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'
        permissions = [
            ('accept_post', 'تایید کردن پست'),
        ]

    title = models.CharField(
        verbose_name='عنوان',
        max_length=200,
    )
    text = tinymce_models.HTMLField(
        verbose_name='متن',
    )
    safe_text = models.TextField(
        verbose_name='متن بدون تگ html',
    )
    image = models.ImageField(
        verbose_name='تصویر پست',
        blank=True,
        null=True,
        upload_to='post_imgs'
    )
    show_post = models.BooleanField(
        verbose_name='نمایش عمومی پست',
        default=True,
    )
    post_send_time = models.DateTimeField(
        verbose_name='زمان ارسال پست',
    )
    accept_by_admin = models.BooleanField(
        verbose_name='پست تایید شده است',
        default=False,
    )
    tags = models.ManyToManyField(
        Tag,
        verbose_name='برچسب ها',
        through='Post_tag',
    )
    categories = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name='دسته بندی ها',
    )
    post_likes = models.ManyToManyField(
        'User',
        verbose_name='پسندیدم',
        blank=True,
        related_name='post_like',
        through='Post_rating',
    )
    user = models.ForeignKey(
        'User',
        on_delete=models.CASCADE,
        verbose_name='کاربر',
        related_name='post_user',
    )

    def __str__(self):
        return self.title

class Post_tag(models.Model):
    class Meta:
        verbose_name = 'برچسب پست'
        verbose_name_plural = 'برچسب های پست'

    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    tag = models.ForeignKey('Tag', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post} : {self.tag}'

class Post_rating(models.Model):
    class Meta:
        verbose_name = 'پسندیدن/نپسندیدن پست'
        verbose_name_plural = 'پسندیدن/نپسندیدن پست ها'
        constraints = [
            models.UniqueConstraint(fields=['post','user'], name='postrates'),
        ]

    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    positive = models.BooleanField(
        verbose_name='پسندیدن؟'
    )

    def __str__(self):
        if self.positive:
            return f'{self.user.username} ' + 'پسندید ' + 'پست ' + f'"{self.post}"'
        else:
            return f'{self.user.username} ' + 'نپسندید ' + 'پست ' + f'"{self.post}"'

class Comment(models.Model):
    class Meta:
        verbose_name = 'نظر'
        verbose_name_plural = 'نظرات'
        permissions = [
            ('accept_comment', 'تایید کردن نظر'),
        ]
        ordering = ['-comment_send_time']
    
    text = models.CharField(
        verbose_name='متن',
        max_length=500,
    )
    accept_by_admin = models.BooleanField(
        verbose_name='کامنت تایید شده است',
        default=False,
    )
    comment_send_time = models.DateTimeField(
        verbose_name='زمان ارسال نظر',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='پست',
    )
    user = models.ForeignKey(
        'User',
        on_delete=models.CASCADE,
        verbose_name='کاربر',
        related_name='comment_user',
    )
    comment_likes = models.ManyToManyField(
        'User',
        verbose_name='پسندیدم',
        blank=True,
        related_name='comment_like',
        through='Comment_rating',
    )

    def __str__(self):
        return str(self.text)[:50] + (len(self.text)>50)*'...'

class Comment_rating(models.Model):
    class Meta:
        verbose_name = 'پسندیدن/نپسندیدن نظر'
        verbose_name_plural = 'پسندیدن/نپسندیدن نظرات'
        constraints = [
            models.UniqueConstraint(fields=['comment','user'], name='commentrates'),
        ]

    comment = models.ForeignKey('Comment', on_delete=models.CASCADE)
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    positive = models.BooleanField(
        verbose_name='پسندیدن؟'
    )

    def __str__(self):
        if self.positive:
            return f'{self.user.username} ' + 'پسندید ' + 'نظر ' + f'"{self.comment}"'
        else:
            return f'{self.user.username} ' + 'نپسندید ' + 'نظر ' + f'"{self.comment}"'

class CustomUserManager(BaseUserManager):
    '''
    Custom user model manager where username is the unique identifiers for authentication
    '''
    def create_user(self, username, password, **extra_fields):
        '''
        Create and save a User with the given username and password.
        '''
        if not username:
            raise ValueError(ugettext_lazy('The Username must be set'))
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, password, **extra_fields):
        '''
        Create and save a SuperUser with the given username and password.
        '''
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(ugettext_lazy('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(ugettext_lazy('Superuser must have is_superuser=True.'))
        return self.create_user(username, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        verbose_name = 'کاربر'
        verbose_name_plural = 'کاربران'

    def validate_username_custom(name):
        if not all([(lambda x: x in printable[:62])(x) for x in name]) or len(str(name)) < 4:
            raise ValidationError(
                ugettext_lazy('%(name)s نمی تواند یک نام کاربری باشد. نام کاربری باید حداقل 4 کاراکتر باشد و فقط می تواند شامل حروف انگلیسی و اعداد باشد.'),
                params={'name': name},
            )

    username = models.CharField(
        verbose_name='نام کاربری',
        max_length=40,
        unique=True,
        primary_key=True,
        validators=[validate_username_custom]
    )
    first_name = models.CharField(
        verbose_name='نام',
        max_length=100,
    )
    last_name = models.CharField(
        verbose_name='نام خانوداگی',
        max_length=100,
    )
    phone_regex = RegexValidator(
        regex=r'\b[0]{1}[9]{1}[0-9]{9}\b',
        message="شماره تلفن همراه باید به فرمت 09123456789 باشد",
    )
    phone = models.CharField(
        verbose_name='تلفن همراه',
        validators=[phone_regex],
        max_length=17,
        blank=True,
        null=True,
    )
    email = models.EmailField(
        verbose_name='ایمیل',
        unique=True,
    )
    birth_day = models.DateField(
        verbose_name='تاریخ تولد',
        blank=True,
        null=True,
    )
    image = models.ImageField(
        verbose_name='تصویر',
        blank=True,
        null=True,
        upload_to='user_imgs'
    )
    date_joined = models.DateTimeField(
        verbose_name='زمان ثبت نام',
        blank=True,
        default=timezone.now,
    )
    is_staff = models.BooleanField(
        verbose_name='کارمند است؟',
        default=False,
    )
    is_active = models.BooleanField(
        verbose_name='فعال است؟',
        default=True,
    )
    is_superuser = models.BooleanField(
        verbose_name='ابرکاربر',
        default=False,
    )
    follow = models.ManyToManyField(
        'User',
        verbose_name='دنبال کنندگان',
        blank=True,
        through='Follow',
    )
    USERNAME_FIELD = 'username'

    objects = CustomUserManager()

    def __str__(self):
        return self.username + ' : ' + self.first_name + " " + self.last_name

class Follow(models.Model):
    class Meta:
        verbose_name = 'ارتباطات کاربران'
        verbose_name_plural = 'ارتباط کاربران'

    follower = models.ForeignKey(
        'User',
        on_delete=models.CASCADE,
        related_name='follower',
    )
    followed = models.ForeignKey(
        'User',
        on_delete=models.CASCADE,
        related_name='followed',
    )

blog/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import Post, User
from django.contrib.auth.password_validation import validate_password


class SearchForm(forms.Form):
    search = forms.CharField(
        max_length=100,
        label='جستجو',
    )
    post_time_sent_from = forms.DateTimeField(
        required=False,
        label='از',
    )
    post_time_sent_to = forms.DateTimeField(
        required=False,
        label='تا',
    )
    title = forms.BooleanField(
        required=False,
        label='عنوان',
    )
    text = forms.BooleanField(
        required=False,
        label='متن',
    )
    tag = forms.BooleanField(
        required=False,
        label='برچسب',
    )
    writer = forms.BooleanField(
        required=False,
        label='نویسنده',
    )


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'text', 'categories', 'show_post']
        widgets = {'text' : TinyMCE()}


class UserForm(forms.ModelForm):
    '''
    This form created for registering to the blog and each user is member of std_user group at first
    '''
    password=forms.CharField(
        label='گذرواژه',
        widget=forms.PasswordInput(),
    )
    confirm_password=forms.CharField(
        label='تکرار گذرواژه',
        widget=forms.PasswordInput(),
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone', 'email', 'birth_day', 'image', 'username', 'password', 'confirm_password']

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        # Here we checked password and confirm password to be same and then do some validation to get strong password
        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("گذرواژه و تکرار آن مطابقت ندارند.")
        validate_password(password)

blog/templates/blog/aboutus.html
{% extends 'blog/base.html' %}

{% load static %}
{% load bootstrap %}
{% load blog_extras %}

{% block title %}درباره ما{% endblock %}

{% block header %}
{% endblock %}

{% block body %}
<br>
سلام
<br>
بلاگ جاییه برای نوشتن و یادگرفتن :)
{% endblock %}

{% block script %}
{% endblock %}

blog/templates/blog/alltags.html
{% extends 'blog/base.html' %}

{% load static %}
{% load bootstrap %}


{% block title %}{{ category }}{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'blog/alltags.css' %}">
{% endblock %}

{% block body %}
    <p>
        تمامی برچسب ها به ترتیب حروف الفبا در زیر امده اند.
        با کلیک بر روی هر برچسب می توانید تمام پسست های این برچسب را مشاهده نمایید.
    </p>
    <div class="d-inline">
        {% for tag in tags %}
            <a href="{% url 'showtag' tag %}">
                <div id="eachTag" class="mt-1 mb-1 pt-1 pb-1">
                    <label>
                        {{ tag }}
                    </label>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/categorybasetree.html
<li>
    {% if passedCategory.category_set.all %}
        <span class="caret text-nowrap">
            <a href="{% url 'showcategory' category %}"> {{ passedCategory.name }}</a>
        </span>
        <ul class="nested">
            {% for category in passedCategory.category_set.all %}
                {% include "blog/categorybasetree.html" with passedCategory=category %}
            {% endfor %}
        </ul>
    {% else %}
        <div class="text-nowrap">
            &nbsp &nbsp <a href="{% url 'showcategory' category %}"> {{ passedCategory.name }}</a>
        </div>
    {% endif %}
</li>

blog/templates/blog/categorytree.html
{% extends 'blog/base.html' %}

{% load static %}
{% load bootstrap %}

{% block title %}دسته بندی ها{% endblock %}

{% block header %}
  <link rel="stylesheet" href="{% static 'blog/categorytree.css' %}"> 
{% endblock %}

{% block body %}

  <p>درختواره دسته بندی ها را در زیر می توانید مشاهده کنید.
   با کلیک بر روی هر دسته می توانید تمام پست های آن دسته بندی را مشاهده نمایید.</p>
  <ul id="myUL"  class="col-3">
    {% for category in categories %}
      {% if not category.supercategory %}
        {% block cg %}
          {% include "blog/categorybasetree.html" with passedCategory=category %}
        {% endblock %}
      {% endif %}
    {% endfor %}
  </ul>

{% endblock %}

{% block script %}
  <script src="{% static 'blog/categorytree.js' %}"></script>
{% endblock %}

blog/templates/blog/commenttag.html
{% load blog_extras %}

<div class="card border-0 mb-3 comment" id="cm{{comment.pk}}">
    <div class="card-header border-0 d-flex" style="background-color: white;">
        <div class="d-flex">
            <div>
                <a href="{% url 'main_profile' comment.user.username %}" style=" color: #363636; text-decoration: none;">
                    {% if comment.user.image  %}
                    <img src="/media/{{ comment.user.image }}" width=38 height=38 
                    style="border-radius: 19px; position: relative; top: 50%; transform: translateY(-50%);">
                    {% else %}
                    <img src="/media/user_imgs/DefaultUserImage.png" width=38 height=38
                    style="border-radius: 19px; position: relative; top: 50%; transform: translateY(-50%);">
                    {% endif %}
                </a>
            </div>
            <div class="me-3">
                <div style="margin-bottom: -2px;">
                    <a href="{% url 'main_profile' comment.user.username %}" style=" color: #363636; text-decoration: none;">
                        {{ comment.user.username }}
                    </a>
                </div>
                <div style="margin-top: -2px; color: #858585; ">
                    {{ comment.comment_send_time|timesince|persian_int }} پیش
                </div>
            </div>
        </div>
    </div>
    <div class="card-body border-0">
        <p class="card-text mt-0">
                {{ comment.text|striptags|truncatewords:12|safe }} 
        </p>
    </div>
    <hr class="mx-3 my-1" />
    <div class="card-footer border-0 d-flex justify-content-between" style="color: #858585; background-color: white;">
        <div class="pt-0 mt-0">
            {% if can_accept %}
                {% if comment.accept_by_admin %}
                    <input class='accept_comment btn bg-primary shadow-none px-1' type='button' value='حذف تایید نظر'>
                {% else %}
                    <input class='accept_comment btn bg-primary shadow-none px-1' type='button' value='تایید نظر'>
                {% endif %}
            {% endif %}
        </div>
        <div class="d-flex pt-2 mt-1">
            <div class="ms-2 d-flex">
                <i class="far fa-thumbs-up fa-lg ms-2 like_comment_btn" style="color: green;"></i>
                
                {% if user.is_authenticated %}
                    {% is_liked_comment_by_user comment user 'like' as is_liked_comment %}
                {% else %}
                    {% is_liked_comment_by_user comment none 'like' as is_liked_comment %}
                {% endif %}

                {% if is_liked_comment %}
                    <div class="like_comment" style="font-weight: 900;">{{ comment|comment_likes|persian_int }}</div>
                {% else %}
                    <div class="like_comment">{{ comment|comment_likes|persian_int }}</div>
                {% endif %}
                
                <div class="d-none">{{ comment|comment_likes }}</div>
            </div>
            <div class="me-2 d-flex">
                <i class="far fa-thumbs-down fa-lg ms-2 dislike_comment_btn" style="color: red;"></i>

                {% if user.is_authenticated %}
                    {% is_liked_comment_by_user comment user 'dislike' as is_disliked_comment %}
                {% else %}
                    {% is_liked_comment_by_user comment none 'dislike' as is_disliked_comment %}
                {% endif %}

                {% if is_disliked_comment %}
                    <div class="dislike_comment" style="font-weight: 900;">{{ comment|comment_dislikes|persian_int }}</div>
                {% else %}
                    <div class="dislike_comment">{{ comment|comment_dislikes|persian_int }}</div>
                {% endif %}
                
                <div class="d-none">{{ comment|comment_dislikes }}</div>
            </div>
        </div>
    </div>
</div>

blog/templates/blog/editpost.html
{% extends 'blog/base.html' %}

{% load static %}
{% load bootstrap %}


{% block title %}ویرایش پست{% endblock %}

{% block header %}

{% endblock %}
    {{ editform.media }}
{% block body %}

    <form id="editPostForm" method="POST" class='w-100 m-auto' enctype="multipart/form-data">
        {% csrf_token %}
        {%for field in editform %}
            <div class="control-group {%if field.errors %}text-danger{%endif%}">
                {{ field|bootstrap }}
            </div>
        {% endfor %}
        <label for="tag">برچسب ها(برای حذف هر برچسب کافی است روی ان کلیک کنید) </label><br>
        <input id="tag" type="search"/>
        <div id="allTags" z-index="1000" class="mt-1" style="overflow-y: scroll; max-height:135px"></div>
        <div name="selectedTags" id="selectedTags" class="mt-1"></div>
        <input type="submit" value="ارسال" class="btn btn-primary mt-2"/>
    </form>
    <br>
{% endblock %}


{% block script %}
    <script src="{% static 'blog/tinymce.min.js' %}"></script>
    <script src="{% static 'blog/editpost.js' %}"></script>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% load static %}
{% load bootstrap %}
{% load blog_extras %}

{% block title %}بلاگ{% endblock %}

{% block header %}
{% endblock %}

{% block body %}
    {% if adv %}
        <div class="d-flex d-wrap">
            <div class="col-12 col-lg-8">
                <div class="d-flex mt-2">
                    <div class="ms-5 sidebarResult">
                        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                            {% for key, value in posts.items %}
                                <a class="nav-link text-center" id="v-pills-{{ key }}-tab" style="min-width: 100px;" data-toggle="pill" href="#v-pills-{{ key }}" role="tab" aria-controls="v-pills-{{ key }}" aria-selected="false">
                                    {{ key|localTranslate }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="mt-2 contentbarResult" style="width: 100%;">
                        <div class="tab-content" id="v-pills-tabContent">
                            {% for key, value in posts.items %}
                                <div class="tab-pane fade" id="v-pills-{{ key }}" role="tabpanel" aria-labelledby="v-pills-{{ key }}-tab">
                                    {% if not value %}
                                        <p>نتیجه ای یافت نشد.</p>
                                    {% else %}
                                        {% for post in value %}
                                            {% include "blog/posttag.html" with post=post %}
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="mostCommentPosts mt-3 px-2 d-none d-lg-block col-lg-4 me-3">
                <p style="font-weight: 700;">جنجالی ترین های بلاگ</p>
                {% for most_comment_post in most_comment_posts %}
                    {% include "blog/mostcommentpost.html" with most_comment_post=most_comment_post %} 
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="d-flex">
            <div class="mt-3 px-2 col-12 col-lg-8">
                {% for post in posts %}
                <div>
                    {% include "blog/posttag.html" with post=post %}
                </div>
                {% endfor %}
            </div>
            <div class="mostCommentPosts mt-3 px-2 d-none d-lg-block col-lg-4 me-3">
                <p style="font-weight: 700;">جنجالی ترین های بلاگ</p>
                {% for most_comment_post in most_comment_posts %}
                    {% include "blog/mostcommentpost.html" with most_comment_post=most_comment_post %} 
                {% endfor %}
            </div>
        </div>
    {% endif %}
    
{% endblock %}

{% block script %}
<script>

    $($('#v-pills-tabContent').children()[0]).addClass('show active')
    $($('#v-pills-tab').children()[0]).addClass('active')

    $('#v-pills-tab a').on('click', function (e) {
    e.preventDefault()
    $(this).tab('show')
    })

    $(document).ready(function() {
        $(document).on('scroll', function() {
            num = window.innerWidth>575 ? 103 : 92
            if( $(document).scrollTop() > num ){
                $('.sidebarResult').attr('style', `margin-top: ${ $(document).scrollTop()-num}px !important`);
            }
            else{
                $('.sidebarResult').removeAttr('style')
            }
        }).trigger('scroll');
    });


    $(document).ready(function() {
        $(document).on('scroll', function() {
            num = window.innerWidth>575 ? 103 : 92
            if( $(document).scrollTop() > num ){
                $('.mostCommentPosts').attr('style', `margin-top: ${ $(document).scrollTop()-num}px !important`);
            }
            else{
                $('.mostCommentPosts').removeAttr('style')
            }
        }).trigger('scroll');
    });

</script>

{% endblock %}

blog/templates/blog/mostcommentpost.html
<div class="d-flex my-3">
    <div>
        <a href="{% url 'main_profile' most_comment_post.user.username %}" style="color: #363636;">
            {% if most_comment_post.user.image  %}
            <img src="/media/{{ most_comment_post.user.image }}" width=38 height=38 
            style="border-radius: 19px; position: relative; top: 50%; transform: translateY(-50%);">
            {% else %}
            <img src="/media/user_imgs/DefaultUserImage.png" width=38 height=38
            style="border-radius: 19px; position: relative; top: 50%; transform: translateY(-50%);">
            {% endif %}
        </a>
    </div>
    <div class="me-3">
        <div style="margin-bottom: -2px;">
            <a href="{% url 'showpost' most_comment_post.user.username most_comment_post.pk %}" style="color: #363636; font-weight: 700; font-size: 0.85rem;">
                {{ most_comment_post.title }}
            </a>
        </div>
        <div style="margin-top: -2px;">
            <a href="{% url 'main_profile' most_comment_post.user.username %}" style=" color: #858585; font-weight: 400; font-size: 0.85rem;">
                {{ most_comment_post.user.first_name }} {{ most_comment_post.user.last_name }}
            </a>
        </div>
    </div>
</div>

blog/templates/blog/newpost.html
{% extends 'blog/base.html' %}

{% load static %}
{% load bootstrap %}


{% block title %}پست جدید{% endblock %}

{% block header %}
    {{ postForm.media }}
{% endblock %}

{% block body %}
    <form id="newPostForm" method="POST" class='w-100 m-auto' enctype="multipart/form-data">
        {% csrf_token %}
        {%for field in postForm %}
            <div class="control-group {% if field.errors %}text-danger{% endif %}">
                {{ field|bootstrap }}
            </div>
        {% endfor %}
        <label for="tag">برچسب ها(برای حذف هر برچسب کافی است روی ان کلیک کنید) </label><br>
        <input id="tag" type="search"/>
        <div id="allTags" z-index="1000" class="mt-1" style="overflow-y: scroll; max-height:135px"></div>
        <div name="selectedTags" id="selectedTags" class="mt-1"></div>
        <div class="mb-1 mt-2">
            <p>در صورتی که می خواهید پست شما در ساعت خاصی ارسال شواد، تاریخ و ساعت آن را در کادر پایین معین کنید</p>
            <input type="date" id="dateScheduledMessage" name="scheduledMessage">
            <input type="time" id="timeScheduledMessage" name="scheduledMessage">
        </div>
        <input type="submit" value="ارسال" class="btn btn-primary mt-2"/>
    </form>
    <br>
{% endblock %}

{% block script %}
    <script src="{% static 'blog/tinymce.min.js' %}"></script>
    <script src="{% static 'blog/newpost.js' %}"></script>
{% endblock %}

blog/templates/blog/newuser.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ثبت نام</title>
</head>
<body>
</body>
</html>

blog/templates/blog/showcategory.html
{% extends 'blog/base.html' %}

{% load static %}
{% load bootstrap %}


{% block title %}{{ category }}{% endblock %}

{% block header %} {% endblock %}

{% block body %}

    <div class="d-flex">
        <div class="mt-3 px-2 col-12 col-lg-8">
            {% if posts %}
                {% for post in posts %}
                <div>
                    {% include "blog/posttag.html" with post=post %}
                </div>
                {% endfor %}
            {% else %}
                <p>در این دسته پستی وجود ندارد.</p>
            {% endif %}
        </div>
        <div class="mostCommentPosts mt-3 px-2 d-none d-lg-block col-lg-4 me-3">
            <p style="font-weight: 700;">جنجالی ترین های بلاگ</p>
            {% for most_comment_post in most_comment_posts %}
                {% include "blog/mostcommentpost.html" with most_comment_post=most_comment_post %} 
            {% endfor %}
        </div>
    </div>

{% endblock %}